---
# infrastructure/ansible/roles/docker/tasks/main.yml

# Install required packages
- name: Install required packages
  apt:
    name: 
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present
    update_cache: yes

# Add Docker GPG key
- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

# Add Docker repository
- name: Add Docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present

# Install Docker
- name: Install Docker
  apt:
    name: docker-ce
    state: present
    update_cache: yes

# Install Docker Compose
- name: Install Docker Compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: '0755'

# Ensure Docker service is running
- name: Ensure Docker service is running
  systemd:
    name: docker
    state: started
    enabled: yes

# Add user to docker group
- name: Add user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

# Human tasks (commented)
# TODO: Review and adjust Docker version and Docker Compose version if needed
# TODO: Verify if additional Docker configurations or optimizations are required for the Apartment Finder web service