# Global configuration
global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

# Rule files
rule_files:
  - "alert_rules.yml"

# Scrape configurations
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Backend monitoring
  - job_name: 'apartment_finder_backend'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['backend:8000']

  # Frontend monitoring
  - job_name: 'apartment_finder_frontend'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['frontend:3000']

  # PostgreSQL monitoring
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  # Redis monitoring
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  # Node exporter for system metrics
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100']

# Human tasks:
# - Review and adjust scrape targets based on the actual deployment architecture
# - Create and configure alert_rules.yml file referenced in rule_files
# - Ensure all services (backend, frontend, postgres, redis) are exposing metrics endpoints