---
# infrastructure/ansible/roles/nginx/tasks/main.yml

# Install Nginx
- name: Install Nginx
  package:
    name: nginx
    state: present

# Ensure Nginx service is running and enabled
- name: Ensure Nginx service is running and enabled
  systemd:
    name: nginx
    state: started
    enabled: yes

# Create Nginx configuration file
- name: Create Nginx configuration file
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: '0644'

# Create Nginx virtual host configuration
- name: Create Nginx virtual host configuration
  template:
    src: apartment_finder.conf.j2
    dest: /etc/nginx/sites-available/apartment_finder.conf
    owner: root
    group: root
    mode: '0644'

# Enable Nginx virtual host
- name: Enable Nginx virtual host
  file:
    src: /etc/nginx/sites-available/apartment_finder.conf
    dest: /etc/nginx/sites-enabled/apartment_finder.conf
    state: link

# Remove default Nginx virtual host
- name: Remove default Nginx virtual host
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

# Reload Nginx to apply changes
- name: Reload Nginx to apply changes
  systemd:
    name: nginx
    state: reloaded

# Human tasks (commented)
# TODO: Review and customize Nginx configuration templates (nginx.conf.j2 and apartment_finder.conf.j2) to ensure they meet specific project requirements
# TODO: Verify SSL certificate paths and configurations if HTTPS is to be implemented